### ISSUE TITLE
loocv for spglm binomial

### ISSUE THREAD

**Issue by ManuelSpinola** [USEPA/spmodel#29]
When doing a spatial spglm binomial, the loocv gives me the RMSPE.  Is that the right performance metric for the spglm model?

**Comment by michaeldumelle** [comment]
@ManuelSpinola thanks for the inquiry! `loocv()` returns the RMSPE between the observed data, $\text{y}$, and the estimated mean, $\hat{\mu}$. We make this comparison on the response scale (i.e., the scale of $\text{y}$) because we observe $\text{y}$ (we don't observe $\mu$ but rather a realization of a random process with mean $\mu$). See our Technical Details Vignette ([linked here](https://usepa.github.io/spmodel/articles/technical.html)) for more.
