### ISSUE TITLE
Residuals not centered around 0

### ISSUE THREAD

**Issue by damondamondamon** [USEPA/spmodel#32]
Hey everybody,

thanks again for the great package, I am using it daily :)

I have a question, that might be more of statistical nature than of your package. I am mostly running models in agricultural contexts like
`f1 <- Yield (continuous) ~ Treatment (categorial) + Soil Taxonomy (categorial) + Terrain (continuous)`
I am usually interested in contrasts of treatments - no problem in assessing those through multcomp/glht. 

Unfortunately, the people I work with are usually not interested in differences alone but also what the absolute yields for different treatments are based on the spatial regression.

I was tackling this in two ways:
- Calculating the _fitted_ values, grouping and summarizing them accordingly:
`local2_list <- list(
  method = "kmeans",
  size = 1000,
  parallel = TRUE,
  ncores = 4)`
`mds <- spmod(formula = f1, data =  data, spcov_type = c("none","spherical"),
                              local = local2_list)) `
`data$fit <- augment(mds$spherical)$.fitted`
`data %>% group_by(Treatment) %>% summarise(mean(fit))`

This will probably not help me in gaining the correct absolute values, which at the same time represent the correct differences in treatments. In essence - the grouped means do not necessarily match my contrasts from the model - at least if the model is not a one-predictor-model.

Still, when I do this, I get much lower absolute values per treatment compared to the original mean of "Yield". When I doublecheck, the mean of my fitted values is 40% smaller than the original mean of Yield. The histogram of residuals are roughly normally distributed but with a drifted mean around 2 instead of 0. Deviating so much seems odd to me, as the model fit could simply be better by just substracting 2 everywhere and by statistical definition residuals should usually be around 0 - but probably I am simply missing something here?
(This is by the way only true for the spherical model though, the non-linear model ("none") returns residuals centered around 0.)

- Calculating the _prediction_ for hypothetical new data that cover all combinations

This is probably the more sensible way, I create a data frame with all combinations of categorial variables (`grid.expand`) and add mean values for the continuous variables. As predictions only work for spatial datasets I add the centroid of the field for each combination - but does this actually go into the calculation? I changed this a bit and predictions stayed the same.
The predictions are still way below the original Yield value - but comparing means between the relevant combinations (here between treatments) at least align with the estimates from the contrasts.

I was wondering if this is specific to my dataset, but found the residuals to not be centered around 0 also for your example dataset:
`spmod < splm(log_Zn ~ log_dist2road, data = moss, spcov_type = "exponential")`
`augment(spmod)$.resid %>% mean`
`-0.7957097`

Any help on this would be much appreciated. I know that I could simply correct my data by adding the bias from the residuals but this does not seem to be an appropriate way to tackle the problem to me.

Thanks a lot in advance!

**Comment by michaeldumelle** [comment]
@damondamondamon thanks for the inquiry and for the kind words about the software -- we really appreciate it! As you have noted, the (raw) residuals in a spatial model are not necessarily centered at zero. This is okay, as we allow these residuals to be correlated! Typically, I recommend people look at routine diagnostics (e.g., residuals vs fitted plots) using the _standardized residuals_, not the raw residuals. The standardized residuals "decorrelate" the process so that it has approximately mean zero, variance one, and no dependence (when the model assumptions are correct).

``` r
library(spmodel)
spmod <- splm(
  formula = log_Zn ~ log_dist2road,
  data = moss,
  spcov_type = "exponential"
)
hist(residuals(spmod))
```

![](https://i.imgur.com/KJxaW6P.png)

``` r
mean(residuals(spmod))
#> [1] -0.7957097
hist(residuals(spmod, type = "standardized"))
```

![](https://i.imgur.com/e9eeNIt.png)

``` r
mean(residuals(spmod, type = "standardized"))
#> [1] -0.1122411
```

<sup>Created on 2024-11-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


The standardized residuals are returned either via `residuals(..., type = "standardized")`, `rstandard()`, or as `.std.resid` from `augment()`.  In fact, they are the default residuals returned by the `plot()` diagnostics.

Now, in regards to your question about treatment effects -- the estimated mean effect is _not necessarily equal_ to the group means from the raw data. This is okay, as the model accounts for spatial dependence! **spmodel** fully supports the **emmeans** package for estimating marginal means, which is especially useful in an experimental design structure like yours. I recommend checking out our "Using emmeans to Estimate Marginal Means of spmodel Objects" vignette ([linked here](https://usepa.github.io/spmodel/articles/emmeans.html)) and the emmeans website ([linked here](https://rvlenth.github.io/emmeans/)) to learn more. If questions remain, don't hesitate to reach back out!
